"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const timer_controller_1 = require("./timer.controller");
const auth_1 = require("../../middleware/auth");
const router = (0, express_1.Router)();
const timerController = new timer_controller_1.TimerController();
router.use(auth_1.authenticateToken);
router.post("/start", timerController.startTimer.bind(timerController));
router.post("/stop", timerController.stopTimer.bind(timerController));
router.post("/pause", timerController.pauseTimer.bind(timerController));
router.get("/:caseControlId/active-time", timerController.getActiveTime.bind(timerController));
exports.default = router;
