"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const todo_controller_1 = require("./todo.controller");
const auth_1 = require("../../middleware/auth");
const auditMiddleware_1 = require("../../middleware/auditMiddleware");
const router = (0, express_1.Router)();
const todoController = new todo_controller_1.TodoController();
router.use(auth_1.authenticateToken);
router.use(auditMiddleware_1.AuditMiddleware.initializeAuditContext);
router.get("/", (req, res) => todoController.getAllTodos(req, res));
router.get("/priorities", (req, res) => todoController.getTodoPriorities(req, res));
router.get("/metrics", (req, res) => todoController.getTodoMetrics(req, res));
router.get("/:id", (req, res) => todoController.getTodoById(req, res));
router.post("/", auditMiddleware_1.AuditMiddleware.auditCreate("todos"), (req, res) => todoController.createTodo(req, res));
router.put("/:id", auditMiddleware_1.AuditMiddleware.auditUpdate("todos"), (req, res) => todoController.updateTodo(req, res));
router.delete("/:id", auditMiddleware_1.AuditMiddleware.auditDelete("todos"), (req, res) => todoController.deleteTodo(req, res));
router.patch("/:id/complete", auditMiddleware_1.AuditMiddleware.auditUpdate("todos"), (req, res) => todoController.completeTodo(req, res));
router.patch("/:id/reactivate", auditMiddleware_1.AuditMiddleware.auditUpdate("todos"), (req, res) => todoController.reactivateTodo(req, res));
router.patch("/:id/archive", auditMiddleware_1.AuditMiddleware.auditUpdate("todos"), (req, res) => todoController.archiveTodo(req, res));
router.post("/:id/start-timer", (req, res) => todoController.startTimer(req, res));
router.post("/:id/pause-timer", (req, res) => todoController.pauseTimer(req, res));
router.get("/:id/time-entries", (req, res) => todoController.getTodoTimeEntries(req, res));
router.delete("/:id/time-entries/:entryId", (req, res) => todoController.deleteTimeEntry(req, res));
router.post("/:id/manual-time-entries", (req, res) => todoController.addManualTimeEntry(req, res));
router.get("/:id/manual-time-entries", (req, res) => todoController.getManualTimeEntries(req, res));
router.delete("/:id/manual-time-entries/:entryId", (req, res) => todoController.deleteManualTimeEntry(req, res));
exports.default = router;
