import { Repository } from "typeorm";
import { SystemParameter, ParameterCategory } from "../entities/SystemParameter";
import { CreateSystemParameterDto } from "../dto/create-system-parameter.dto";
import { UpdateSystemParameterDto } from "../dto/update-system-parameter.dto";
export declare class SystemParameterService {
    private readonly systemParameterRepository;
    private parameterCache;
    private cacheExpiry;
    private readonly CACHE_DURATION;
    private readonly ENCRYPTION_KEY;
    constructor(systemParameterRepository: Repository<SystemParameter>);
    private encrypt;
    private decrypt;
    findAll(): Promise<SystemParameter[]>;
    findByCategory(category: ParameterCategory): Promise<SystemParameter[]>;
    findByKey(key: string): Promise<SystemParameter | null>;
    getValue<T = any>(key: string): Promise<T | null>;
    setValue(key: string, value: any, userId?: string): Promise<SystemParameter>;
    create(createDto: CreateSystemParameterDto, userId?: string): Promise<SystemParameter>;
    update(id: number, updateDto: UpdateSystemParameterDto, userId?: string): Promise<SystemParameter>;
    remove(id: number, userId?: string): Promise<void>;
    getConfigByCategory(category: ParameterCategory): Promise<Record<string, any>>;
    validateRequiredParameters(): Promise<string[]>;
    getConfigurationStats(): Promise<any>;
    private getCachedValue;
    private setCachedValue;
    private invalidateCache;
    private initializeCache;
    refreshCache(): Promise<void>;
}
