"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const case_control_controller_1 = require("./case-control.controller");
const auth_1 = require("../../middleware/auth");
const router = (0, express_1.Router)();
const caseControlController = new case_control_controller_1.CaseControlController();
router.use(auth_1.authenticateToken);
router.get("/statuses", caseControlController.getCaseStatuses.bind(caseControlController));
router.get("/", caseControlController.getAllCaseControls.bind(caseControlController));
router.get("/:id", caseControlController.getCaseControlById.bind(caseControlController));
router.post("/", caseControlController.createCaseControl.bind(caseControlController));
router.put("/:id/status", caseControlController.updateCaseControlStatus.bind(caseControlController));
router.delete("/:id", caseControlController.deleteCaseControl.bind(caseControlController));
router.get("/:id/time-entries", caseControlController.getTimeEntries.bind(caseControlController));
router.get("/:id/manual-time-entries", caseControlController.getManualTimeEntries.bind(caseControlController));
router.post("/:id/manual-time-entries", caseControlController.addManualTimeEntry.bind(caseControlController));
router.delete("/:id/manual-time-entries/:entryId", caseControlController.deleteManualTimeEntry.bind(caseControlController));
router.delete("/:id/time-entries/:entryId", caseControlController.deleteTimeEntry.bind(caseControlController));
exports.default = router;
