"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const case_controller_1 = require("./case.controller");
const auth_1 = require("../../middleware/auth");
const auditMiddleware_1 = require("../../middleware/auditMiddleware");
const authorizationMiddleware_1 = require("../../middleware/authorizationMiddleware");
const router = (0, express_1.Router)();
router.use(auth_1.authenticateToken);
router.use(auditMiddleware_1.AuditMiddleware.initializeAuditContext);
router.get("/stats", (0, authorizationMiddleware_1.requirePermission)("cases.view.own"), case_controller_1.getCaseStats);
router.get("/", (0, authorizationMiddleware_1.requirePermission)("cases.view.own"), case_controller_1.getCases);
router.get("/:id", (0, authorizationMiddleware_1.requirePermission)("cases.view.own"), case_controller_1.getCaseById);
router.post("/", (0, authorizationMiddleware_1.requirePermission)("cases.create.own"), auditMiddleware_1.AuditMiddleware.auditCreate("cases"), case_controller_1.createCase);
router.put("/:id", (0, authorizationMiddleware_1.requirePermission)("cases.edit.own"), auditMiddleware_1.AuditMiddleware.auditUpdate("cases"), case_controller_1.updateCase);
router.delete("/:id", (0, authorizationMiddleware_1.requirePermission)("cases.delete.own"), auditMiddleware_1.AuditMiddleware.auditDelete("cases"), case_controller_1.deleteCase);
exports.default = router;
