"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.applicationRoutes = void 0;
const express_1 = require("express");
const ApplicationController_1 = require("../controllers/ApplicationController");
const auth_1 = require("../middleware/auth");
const auditMiddleware_1 = require("../middleware/auditMiddleware");
const router = (0, express_1.Router)();
exports.applicationRoutes = router;
const applicationController = new ApplicationController_1.ApplicationController();
router.use(auth_1.authenticateToken);
router.use(auditMiddleware_1.AuditMiddleware.initializeAuditContext);
router.get("/", applicationController.getAllApplications.bind(applicationController));
router.get("/search", applicationController.searchApplications.bind(applicationController));
router.get("/stats", applicationController.getApplicationStats.bind(applicationController));
router.get("/:id", applicationController.getApplicationById.bind(applicationController));
router.post("/", auditMiddleware_1.AuditMiddleware.auditCreate("aplicaciones"), applicationController.createApplication.bind(applicationController));
router.put("/:id", auditMiddleware_1.AuditMiddleware.auditUpdate("aplicaciones"), applicationController.updateApplication.bind(applicationController));
router.delete("/:id", auditMiddleware_1.AuditMiddleware.auditDelete("aplicaciones"), applicationController.deleteApplication.bind(applicationController));
router.get("/:id/can-delete", applicationController.checkCanDeleteApplication.bind(applicationController));
