"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.caseStatusRoutes = void 0;
const express_1 = require("express");
const CaseStatusController_1 = require("../controllers/CaseStatusController");
const auth_1 = require("../middleware/auth");
const auditMiddleware_1 = require("../middleware/auditMiddleware");
const router = (0, express_1.Router)();
exports.caseStatusRoutes = router;
const caseStatusController = new CaseStatusController_1.CaseStatusController();
router.use(auth_1.authenticateToken);
router.use(auditMiddleware_1.AuditMiddleware.initializeAuditContext);
router.get("/", caseStatusController.getAllStatuses.bind(caseStatusController));
router.get("/search", caseStatusController.searchStatuses.bind(caseStatusController));
router.get("/stats", caseStatusController.getStatusStats.bind(caseStatusController));
router.get("/active", caseStatusController.getActiveStatusesOrdered.bind(caseStatusController));
router.get("/:id", caseStatusController.getStatusById.bind(caseStatusController));
router.post("/", auditMiddleware_1.AuditMiddleware.auditCreate("case_status_control"), caseStatusController.createStatus.bind(caseStatusController));
router.put("/:id", auditMiddleware_1.AuditMiddleware.auditUpdate("case_status_control"), caseStatusController.updateStatus.bind(caseStatusController));
router.put("/reorder", auditMiddleware_1.AuditMiddleware.auditUpdate("case_status_control"), caseStatusController.reorderStatuses.bind(caseStatusController));
router.delete("/:id", auditMiddleware_1.AuditMiddleware.auditDelete("case_status_control"), caseStatusController.deleteStatus.bind(caseStatusController));
router.get("/:id/can-delete", caseStatusController.checkCanDeleteStatus.bind(caseStatusController));
