"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const SystemInfoController_1 = require("../controllers/SystemInfoController");
const auth_1 = require("../middleware/auth");
const router = (0, express_1.Router)();
const systemInfoController = new SystemInfoController_1.SystemInfoController();
router.get("/version", systemInfoController.getVersion.bind(systemInfoController));
router.get("/info", auth_1.authenticateToken, systemInfoController.getSystemInfo.bind(systemInfoController));
router.get("/modules", auth_1.authenticateToken, systemInfoController.getModules.bind(systemInfoController));
router.get("/changelog", auth_1.authenticateToken, systemInfoController.getChangelog.bind(systemInfoController));
router.get("/stats", auth_1.authenticateToken, systemInfoController.getStats.bind(systemInfoController));
exports.default = router;
