"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.teamRoutes = void 0;
const express_1 = require("express");
const TeamController_1 = require("../controllers/TeamController");
const auth_1 = require("../middleware/auth");
const TeamAuthorizationMiddleware_1 = require("../middleware/TeamAuthorizationMiddleware");
const auditMiddleware_1 = require("../middleware/auditMiddleware");
const router = (0, express_1.Router)();
exports.teamRoutes = router;
const teamController = new TeamController_1.TeamController();
router.use(auth_1.authenticateToken);
router.use(auditMiddleware_1.AuditMiddleware.initializeAuditContext);
router.get("/", (0, TeamAuthorizationMiddleware_1.requireAnyPermission)(["teams.view.all"]), teamController.getAllTeams);
router.post("/", (0, TeamAuthorizationMiddleware_1.requireAnyPermission)(["teams.create.all"]), auditMiddleware_1.AuditMiddleware.auditCreate("teams"), teamController.createTeam);
router.get("/:id", (0, TeamAuthorizationMiddleware_1.requireAnyPermission)(["teams.view.all"]), teamController.getTeamById);
router.put("/:id", (0, TeamAuthorizationMiddleware_1.requireAnyPermission)(["teams.edit.all"]), auditMiddleware_1.AuditMiddleware.auditUpdate("teams"), teamController.updateTeam);
router.delete("/:id", (0, TeamAuthorizationMiddleware_1.requireAnyPermission)(["teams.delete.all"]), auditMiddleware_1.AuditMiddleware.auditDelete("teams"), teamController.deleteTeam);
router.patch("/:id/toggle-status", (0, TeamAuthorizationMiddleware_1.requireAnyPermission)(["teams.edit.all"]), auditMiddleware_1.AuditMiddleware.auditUpdate("teams"), teamController.toggleTeamStatus);
router.get("/:teamId/members", (0, TeamAuthorizationMiddleware_1.requireAnyPermission)(["teams.view.all", "teams.manage.members"]), teamController.getTeamMembers);
router.post("/:teamId/members", (0, TeamAuthorizationMiddleware_1.requireAnyPermission)(["teams.manage.members"]), auditMiddleware_1.AuditMiddleware.auditCreate("team_members"), teamController.addTeamMember);
router.put("/:teamId/members/:memberId", (0, TeamAuthorizationMiddleware_1.requireAnyPermission)(["teams.manage.members"]), auditMiddleware_1.AuditMiddleware.auditUpdate("team_members"), teamController.updateTeamMember);
router.patch("/:teamId/members/:memberId/role", (0, TeamAuthorizationMiddleware_1.requireAnyPermission)(["teams.manage.members"]), auditMiddleware_1.AuditMiddleware.auditUpdate("team_members"), teamController.updateMemberRole);
router.delete("/:teamId/members/:memberId", (0, TeamAuthorizationMiddleware_1.requireAnyPermission)(["teams.manage.members"]), auditMiddleware_1.AuditMiddleware.auditDelete("team_members"), teamController.removeTeamMember);
router.patch("/:teamId/transfer-leadership", (0, TeamAuthorizationMiddleware_1.requireAnyPermission)(["teams.manage.members"]), auditMiddleware_1.AuditMiddleware.auditUpdate("team_members"), teamController.transferLeadership);
router.post("/:teamId/members/bulk", (0, TeamAuthorizationMiddleware_1.requireAnyPermission)(["teams.manage.members"]), auditMiddleware_1.AuditMiddleware.auditCreate("team_members"), teamController.addBulkMembers);
router.get("/user/my-teams", teamController.getMyTeams);
router.get("/user/:userId/membership/:teamId", (0, TeamAuthorizationMiddleware_1.requireAnyPermission)(["teams.view.all"]), teamController.checkUserMembership);
router.get("/:teamId/stats", (0, TeamAuthorizationMiddleware_1.requireAnyPermission)(["teams.view.all"]), teamController.getTeamStats);
