"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.todoPriorityRoutes = void 0;
const express_1 = require("express");
const TodoPriorityController_1 = require("../controllers/TodoPriorityController");
const auth_1 = require("../middleware/auth");
const auditMiddleware_1 = require("../middleware/auditMiddleware");
const router = (0, express_1.Router)();
exports.todoPriorityRoutes = router;
const todoPriorityController = new TodoPriorityController_1.TodoPriorityController();
router.use(auth_1.authenticateToken);
router.use(auditMiddleware_1.AuditMiddleware.initializeAuditContext);
router.get("/", todoPriorityController.getAllPriorities.bind(todoPriorityController));
router.get("/stats", todoPriorityController.getPriorityStats.bind(todoPriorityController));
router.get("/:id", todoPriorityController.getPriorityById.bind(todoPriorityController));
router.post("/", auditMiddleware_1.AuditMiddleware.auditCreate("todo_priorities"), todoPriorityController.createPriority.bind(todoPriorityController));
router.put("/:id", auditMiddleware_1.AuditMiddleware.auditUpdate("todo_priorities"), todoPriorityController.updatePriority.bind(todoPriorityController));
router.put("/:id/toggle", auditMiddleware_1.AuditMiddleware.auditUpdate("todo_priorities"), todoPriorityController.togglePriorityStatus.bind(todoPriorityController));
router.delete("/:id", auditMiddleware_1.AuditMiddleware.auditDelete("todo_priorities"), todoPriorityController.deletePriority.bind(todoPriorityController));
router.put("/reorder", auditMiddleware_1.AuditMiddleware.auditUpdate("todo_priorities"), todoPriorityController.reorderPriorities.bind(todoPriorityController));
