"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TeamMember = exports.Team = exports.AuditEntityChange = exports.AuditLog = exports.DocumentType = exports.KnowledgeDocumentTagRelation = exports.KnowledgeDocumentTag = exports.KnowledgeTag = exports.KnowledgeDocumentRelation = exports.KnowledgeDocumentFeedback = exports.KnowledgeDocumentVersion = exports.KnowledgeDocumentAttachment = exports.KnowledgeDocument = exports.ArchivedTodo = exports.ArchivedCaseClassification = exports.ArchivedCasePriority = exports.ArchivedCaseStatus = exports.ArchivedCase = exports.Note = exports.TodoManualTimeEntry = exports.TodoTimeEntry = exports.TodoControl = exports.TodoPriority = exports.Todo = exports.Disposition = exports.ManualTimeEntry = exports.TimeEntry = exports.CaseControl = exports.CaseStatusControl = exports.EstadoCase = exports.ClasificacionCase = exports.Case = exports.Origin = exports.Application = exports.UserProfile = exports.RolePermission = exports.Permission = exports.Role = void 0;
var Role_1 = require("./Role");
Object.defineProperty(exports, "Role", { enumerable: true, get: function () { return Role_1.Role; } });
var Permission_1 = require("./Permission");
Object.defineProperty(exports, "Permission", { enumerable: true, get: function () { return Permission_1.Permission; } });
var RolePermission_1 = require("./RolePermission");
Object.defineProperty(exports, "RolePermission", { enumerable: true, get: function () { return RolePermission_1.RolePermission; } });
var UserProfile_1 = require("./UserProfile");
Object.defineProperty(exports, "UserProfile", { enumerable: true, get: function () { return UserProfile_1.UserProfile; } });
var Application_1 = require("./Application");
Object.defineProperty(exports, "Application", { enumerable: true, get: function () { return Application_1.Application; } });
var Origin_1 = require("./Origin");
Object.defineProperty(exports, "Origin", { enumerable: true, get: function () { return Origin_1.Origin; } });
var Case_1 = require("./Case");
Object.defineProperty(exports, "Case", { enumerable: true, get: function () { return Case_1.Case; } });
Object.defineProperty(exports, "ClasificacionCase", { enumerable: true, get: function () { return Case_1.ClasificacionCase; } });
Object.defineProperty(exports, "EstadoCase", { enumerable: true, get: function () { return Case_1.EstadoCase; } });
var CaseStatusControl_1 = require("./CaseStatusControl");
Object.defineProperty(exports, "CaseStatusControl", { enumerable: true, get: function () { return CaseStatusControl_1.CaseStatusControl; } });
var CaseControl_1 = require("./CaseControl");
Object.defineProperty(exports, "CaseControl", { enumerable: true, get: function () { return CaseControl_1.CaseControl; } });
var TimeEntry_1 = require("./TimeEntry");
Object.defineProperty(exports, "TimeEntry", { enumerable: true, get: function () { return TimeEntry_1.TimeEntry; } });
var ManualTimeEntry_1 = require("./ManualTimeEntry");
Object.defineProperty(exports, "ManualTimeEntry", { enumerable: true, get: function () { return ManualTimeEntry_1.ManualTimeEntry; } });
var Disposition_1 = require("./Disposition");
Object.defineProperty(exports, "Disposition", { enumerable: true, get: function () { return Disposition_1.Disposition; } });
var Todo_1 = require("./Todo");
Object.defineProperty(exports, "Todo", { enumerable: true, get: function () { return Todo_1.Todo; } });
var TodoPriority_1 = require("./TodoPriority");
Object.defineProperty(exports, "TodoPriority", { enumerable: true, get: function () { return TodoPriority_1.TodoPriority; } });
var TodoControl_1 = require("./TodoControl");
Object.defineProperty(exports, "TodoControl", { enumerable: true, get: function () { return TodoControl_1.TodoControl; } });
var TodoTimeEntry_1 = require("./TodoTimeEntry");
Object.defineProperty(exports, "TodoTimeEntry", { enumerable: true, get: function () { return TodoTimeEntry_1.TodoTimeEntry; } });
var TodoManualTimeEntry_1 = require("./TodoManualTimeEntry");
Object.defineProperty(exports, "TodoManualTimeEntry", { enumerable: true, get: function () { return TodoManualTimeEntry_1.TodoManualTimeEntry; } });
var Note_1 = require("./Note");
Object.defineProperty(exports, "Note", { enumerable: true, get: function () { return Note_1.Note; } });
var ArchivedCase_1 = require("./ArchivedCase");
Object.defineProperty(exports, "ArchivedCase", { enumerable: true, get: function () { return ArchivedCase_1.ArchivedCase; } });
Object.defineProperty(exports, "ArchivedCaseStatus", { enumerable: true, get: function () { return ArchivedCase_1.ArchivedCaseStatus; } });
Object.defineProperty(exports, "ArchivedCasePriority", { enumerable: true, get: function () { return ArchivedCase_1.ArchivedCasePriority; } });
Object.defineProperty(exports, "ArchivedCaseClassification", { enumerable: true, get: function () { return ArchivedCase_1.ArchivedCaseClassification; } });
var ArchivedTodo_entity_1 = require("./archive/ArchivedTodo.entity");
Object.defineProperty(exports, "ArchivedTodo", { enumerable: true, get: function () { return ArchivedTodo_entity_1.ArchivedTodo; } });
var KnowledgeDocument_1 = require("./KnowledgeDocument");
Object.defineProperty(exports, "KnowledgeDocument", { enumerable: true, get: function () { return KnowledgeDocument_1.KnowledgeDocument; } });
var KnowledgeDocumentAttachment_1 = require("./KnowledgeDocumentAttachment");
Object.defineProperty(exports, "KnowledgeDocumentAttachment", { enumerable: true, get: function () { return KnowledgeDocumentAttachment_1.KnowledgeDocumentAttachment; } });
var KnowledgeDocumentVersion_1 = require("./KnowledgeDocumentVersion");
Object.defineProperty(exports, "KnowledgeDocumentVersion", { enumerable: true, get: function () { return KnowledgeDocumentVersion_1.KnowledgeDocumentVersion; } });
var KnowledgeDocumentFeedback_1 = require("./KnowledgeDocumentFeedback");
Object.defineProperty(exports, "KnowledgeDocumentFeedback", { enumerable: true, get: function () { return KnowledgeDocumentFeedback_1.KnowledgeDocumentFeedback; } });
var KnowledgeDocumentRelation_1 = require("./KnowledgeDocumentRelation");
Object.defineProperty(exports, "KnowledgeDocumentRelation", { enumerable: true, get: function () { return KnowledgeDocumentRelation_1.KnowledgeDocumentRelation; } });
var KnowledgeTag_1 = require("./KnowledgeTag");
Object.defineProperty(exports, "KnowledgeTag", { enumerable: true, get: function () { return KnowledgeTag_1.KnowledgeTag; } });
var KnowledgeDocumentTag_1 = require("./KnowledgeDocumentTag");
Object.defineProperty(exports, "KnowledgeDocumentTag", { enumerable: true, get: function () { return KnowledgeDocumentTag_1.KnowledgeDocumentTag; } });
var KnowledgeDocumentTagRelation_1 = require("./KnowledgeDocumentTagRelation");
Object.defineProperty(exports, "KnowledgeDocumentTagRelation", { enumerable: true, get: function () { return KnowledgeDocumentTagRelation_1.KnowledgeDocumentTagRelation; } });
var DocumentType_1 = require("./DocumentType");
Object.defineProperty(exports, "DocumentType", { enumerable: true, get: function () { return DocumentType_1.DocumentType; } });
var AuditLog_1 = require("./AuditLog");
Object.defineProperty(exports, "AuditLog", { enumerable: true, get: function () { return AuditLog_1.AuditLog; } });
var AuditEntityChange_1 = require("./AuditEntityChange");
Object.defineProperty(exports, "AuditEntityChange", { enumerable: true, get: function () { return AuditEntityChange_1.AuditEntityChange; } });
var Team_1 = require("./Team");
Object.defineProperty(exports, "Team", { enumerable: true, get: function () { return Team_1.Team; } });
var TeamMember_1 = require("./TeamMember");
Object.defineProperty(exports, "TeamMember", { enumerable: true, get: function () { return TeamMember_1.TeamMember; } });
