import { UserProfile } from "./UserProfile";
import { DocumentType } from "./DocumentType";
import { KnowledgeDocumentTag } from "./KnowledgeDocumentTag";
import { KnowledgeDocumentTagRelation } from "./KnowledgeDocumentTagRelation";
import { KnowledgeDocumentVersion } from "./KnowledgeDocumentVersion";
import { KnowledgeDocumentAttachment } from "./KnowledgeDocumentAttachment";
import { KnowledgeDocumentRelation } from "./KnowledgeDocumentRelation";
import { KnowledgeDocumentFeedback } from "./KnowledgeDocumentFeedback";
export type Priority = "low" | "medium" | "high" | "urgent";
export declare class KnowledgeDocument {
    id: string;
    title: string;
    content: string | null;
    jsonContent: object;
    documentTypeId: string | null;
    documentType: Promise<DocumentType>;
    priority: Priority;
    difficultyLevel: number;
    isPublished: boolean;
    isTemplate: boolean;
    isDeprecated: boolean;
    isArchived: boolean;
    viewCount: number;
    helpfulCount: number;
    notHelpfulCount: number;
    version: number;
    publishedAt: Date | null;
    deprecatedAt: Date | null;
    archivedAt: Date | null;
    createdBy: string;
    createdByUser: Promise<UserProfile>;
    lastEditedBy: string | null;
    lastEditedByUser: Promise<UserProfile>;
    archivedBy: string | null;
    archivedByUser: Promise<UserProfile>;
    replacementDocumentId: string | null;
    replacementDocument: Promise<KnowledgeDocument>;
    tagsJson: string[];
    associatedCases: string[];
    tags: KnowledgeDocumentTag[];
    tagRelations: KnowledgeDocumentTagRelation[];
    versions: KnowledgeDocumentVersion[];
    attachments: KnowledgeDocumentAttachment[];
    parentRelations: KnowledgeDocumentRelation[];
    childRelations: KnowledgeDocumentRelation[];
    feedback: KnowledgeDocumentFeedback[];
    createdAt: Date;
    updatedAt: Date;
}
