import { Case } from "./Case";
import { UserProfile } from "./UserProfile";
export declare class Note {
    id: string;
    title: string;
    content: string;
    noteType: string;
    priority: string;
    difficultyLevel: number;
    tags: string[];
    caseId?: string;
    createdBy: string;
    assignedTo?: string;
    isImportant: boolean;
    isArchived: boolean;
    isTemplate: boolean;
    isPublished: boolean;
    isDeprecated: boolean;
    viewCount: number;
    helpfulCount: number;
    notHelpfulCount: number;
    version: number;
    archivedAt?: Date;
    archivedBy?: string;
    reminderDate?: Date;
    isReminderSent: boolean;
    complexityNotes?: string;
    prerequisites?: string;
    estimatedSolutionTime?: number;
    deprecationReason?: string;
    replacementNoteId?: string;
    lastReviewedAt?: Date;
    lastReviewedBy?: string;
    createdAt: Date;
    updatedAt: Date;
    case?: Case;
    createdByUser: UserProfile;
    assignedToUser?: UserProfile;
    archivedByUser?: UserProfile;
    replacementNote?: Note;
}
